### ISSUE TITLE
Which method to override  for async operations? `main` or `start` ?

### ISSUE THREAD

**Issue by PrideChung** [stanislaw/CompositeOperations#4]
As `NSOperation`'s documentation states, I should override `- start` for async operations, but in your example it overrided `- main`, this is confusing.

**Comment by PrideChung** [comment]
OK, `main` it is.

**Comment by stanislaw** [comment]
@PrideChung you're right: the `main` method is to be overriden.

I am not sure if that is still actual to you but here's the rationale behind it:

Both simple and composite operations are based on `COAbstractOperation` class which contains implementation of state machine (let's call it "proto-" state machine). To handle the general flow of operation that class has the [following overrides](https://github.com/stanislaw/CompositeOperations/blob/52819f1ae5361fa25db693b61915b622387ddb9a/CompositeOperations/COAbstractOperation.m#L47) of `start` method:

```objective-c
- (void)start {
    if (self.isReady) {
        self.state = COOperationStateExecuting;

        if (self.isCancelled) {
            self.state = COOperationStateFinished;
        } else {
            [self main];
        }
    }
}
```

So having that in place the only thing you need to do to create your own subclass of `COSimpleOperation` is to just override its operation body i.e. the `main` method and to make sure that you have `-finishWithResult` or `rejectWithError:` methods at some point.

I hope that makes sense. Do you think that this needs to be clarified in documentation?
